### ISSUE TITLE
Plugin refactoring

### ISSUE THREAD

**Issue by mecachisenros** [mecachisenros/woocommerce_civicrm#15]
This is not an issue but rather a question.

I've recently run into a small issue with the latest WC 3.0+ where the order properties cannot be accessed directly anymore (protected properties) and we have to use getter methods like `get_billing_email()` so I've gave it a go and refactored the plugin aiming for, hopefully, get it ready for publishing in the WordPress plugin directory. 

The question: would you @veda-consulting be interested in publishing it?

I've created a [v2.0 branch](https://github.com/mecachisenros/woocommerce_civicrm/tree/v2.0), I can prepare a PR and I'll be happy to help improving the integration.

**Comment by mecachisenros** [comment]
@veda-consulting  I've made a few more improvements, support for State/Province, added a few hooks and an option to sync woocommerce/civicrm mapped addresses both ways #4

**Comment by veda-consulting** [comment]
@mecachisenros thanks for those, if you can prepare a PR we would be happy to release version 2.0

**Comment by mecachisenros** [comment]
@veda-consulting perfect, I just need to push a couple more fixes and then I'll prepare the PR, ETA tomorrow evening

**Comment by mecachisenros** [comment]
@veda-consulting as promised, PR created, feel free to review/ask clarifications

**Comment by veda-consulting** [comment]
Great thanks, we'll get onto it

Parvez Saleh

Managing Director

 vedaconsulting.co.uk

 +44 (0) 33 3011 8874 <#UNIQUE_ID_SafeHtmlFilter_>

 90 Mainyard, 90 Wallis Rd
London, E9 5LN

<https://twitter.com/vedaconsulting>
<https://www.facebook.com/vedaconsulting>
<https://uk.linkedin.com/in/vedaconsulting>
