### ISSUE TITLE
CiviCRM API3 exceptions not caught

### ISSUE THREAD

**Issue by mjwright** [mecachisenros/woocommerce_civicrm#17]
Exceptions to all civicrm_api3 calls are not caught. API3 exceptions throw CiviCRM_API3_Exception, but this plugin only catches CiviCRM_Exception. Need to change all catches to CiviCRM_API3_Exception.

This is noticeable when the user attempts to change their Billing Address through the WooCommerce My Account Billing Address page when there is no Billing Address in CiviCRM resulting in:
PHP Fatal error:  Uncaught CiviCRM_API3_Exception: [undefined: Expected one Address but found 0

**Comment by mecachisenros** [comment]
@mjwright that's been address in [v2.1](https://github.com/mecachisenros/woocommerce_civicrm/commit/5b771fd0867312d154b02e263145dd84308f4da7) in my [fork](https://github.com/mecachisenros/woocommerce_civicrm), which also removes the need of the [CiviCRM extension](https://github.com/veda-consulting/uk.co.vedaconsulting.module.woocommercecivicrm).

I haven't submitted a PR as I haven't tested it fully, so if you do try v2.1 do it in a dev environment.

**Comment by mecachisenros** [comment]
@mjwright this should be addressed in the current `master` branch.
