### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jmdziba** [mecachisenros/woocommerce_civicrm#2]
Is this:  uk.co.vedaconsulting.module.woocommercecivicrm
being installed as a regular WORDPRESS PLUGIN as well, or as a CiviCRM EXTENSION?

**Comment by rajeshrhino** [comment]
@jmdziba  uk.co.vedaconsulting.module.woocommercecivicrm should be installed as CiviCRM extension. We have updated the instructions in README file to make it clear.
