### ISSUE TITLE
Orders not showing up in WooCommerce orders tab on Civicrm

### ISSUE THREAD

**Issue by netzih** [mecachisenros/woocommerce_civicrm#29]
While I finally got the contributions and contacts to be created successfully using the patch in #27 it seems the orders are still not coming up in the woocommerce orders tab on Civicrm contact page.
Any reason that would be?

**Comment by mjwright** [comment]
Orders only show in the orders tab when the contact has a user framework ID (i.e. a WordPress login account). Orders placed by contacts without a UID (anonymous users) do not show in the orders tab.

**Comment by netzih** [comment]
Thank you for the quick reply.
Is there a way to change that and show orders even for anonymous users?

**Comment by mecachisenros** [comment]
@netzih thanks to @mjwright via #30 the Orders tab should show for both type of contacts, anonymous and _synced_ (WP user assigned).
