### ISSUE TITLE
CiviCRM TAB doesn't show in Woocommerce

### ISSUE THREAD

**Issue by alexletizia** [mecachisenros/woocommerce_civicrm#31]
Hi all,

on Wordpress 5.5.3  - Woocommerce 4.7.1 -  CiviCRM 5.29.1  -  PHP 7.3.19

CiviCRM TAB doesn't show in Woocommerce  even if the plugin is correctly installed:

![CiviCRM - Woocommerce ITA TAB doesn't show](https://user-images.githubusercontent.com/40597363/100270050-c1804000-2f57-11eb-8f82-128af8edb245.jpg)

We installed it as a normal Wordpress .zip plugin, we are right?

Do you have notice of incompatibility between the CiviCRM / Woommerce plugin and the latest version of Woocommerce or Wordpress? 

I don't think it could be a problem related to the latest version of CiviCRM and we ha disabled all other WP Plugin on this host.

**Comment by alexletizia** [comment]
We installed it as a normal Wordpress .zip plugin, we are right?

**Comment by alexletizia** [comment]
> Hi all,
> 
> on Wordpress 5.5.3 - Woocommerce 4.7.1 - CiviCRM 5.29.1 :
> 
> CiviCRM TAB doesn't show in Woocommerce even if the plugin is correctly installed:
> 
> ![CiviCRM - Woocommerce ITA TAB doesn't show](https://user-images.githubusercontent.com/40597363/100270050-c1804000-2f57-11eb-8f82-128af8edb245.jpg)

We installed it as a normal Wordpress .zip plugin, we are right?

**Comment by mecachisenros** [comment]
@alexletizia 09566d6 should address it, I suggest you clear CiviCRM's cache after updating the plugin.

**Comment by alexletizia** [comment]
> @alexletizia [09566d6](https://github.com/mecachisenros/woocommerce_civicrm/commit/09566d6ef49b883ea62d519c05b4810276362463) should address it, I suggest you clear CiviCRM's cache after updating the plugin.

**Comment by alexletizia** [comment]
Ok, with the file upgrade now everything works correctly. Thx a lot.
