### ISSUE TITLE
Syncing billing address between woocommerce and CiviCRM

### ISSUE THREAD

**Issue by bradydan** [mecachisenros/woocommerce_civicrm#4]
Can this plugin be used to sync billing address from WooCommerce to CiviCRM (and vice versa)?

I notice that the plugin settings page does seem to imply that this should work, but nothing is syncing for existing users and contacts 

p.s. I notice that there's [a fork of this plugin which adds VAT handling](https://github.com/mecachisenros/woocommerce_civicrm) - any plans to merge these changes?

**Comment by veda-consulting** [comment]
@bradydan the VAT changes have been pulled into the repo now. Please do take a look. The addresses will only sync during purchases.

**Comment by bradydan** [comment]
Thanks for pulling those VAT changes.

Any chance of this plugin being added to the WordPress plugin repository? As you will know, it's the easiest way of keeping plugins up-to-date.

**Comment by veda-consulting** [comment]
@bradydan yes, I think we can do that. We will try and push in the coming week or so.

**Comment by bradydan** [comment]
👍
