### ISSUE TITLE
Api call causes fatal error

### ISSUE THREAD

**Issue by redcuillin** [mecachisenros/woocommerce_civicrm#6]
I have CiviCRM 4.4.4 running on Wordpress 4.5+. 

Trying to use the WooCommerce CiviCRM plugin, but I get the following fatal error when trying the settings page: "Uncaught CiviCRM_API3_Exception: [undefined: API (FinancialType, get) does not exist"

I've checked my CiviCRM installation, and there is indeed no such API functionality.

Is this because of a change the API or something?

**Comment by redcuillin** [comment]
Upgrading to 4.7.7 resolved the problem. Not sure why API functionality was missing, as it should have been in 4.4.4., but anyway ...

**Comment by veda-consulting** [comment]
in 4.4 financial type was known as contribution type, hence it probably
failed.

Extension is only 4.6+ compatible anyway

Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by JoeMurray** [comment]
Issue can be closed.
